name: CI Процесс

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    branches:
      - develop
      - release/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Репозиторио татах
      - uses: actions/checkout@v4

      # JDK 17 тохируулах
      - name: JDK 17 Тохируулах
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Checkstyle шалгах
      - name: Checkstyle Шалгах
        run: mvn checkstyle:check
        working-directory: ./src

      # JUnit тест болон Jacoco coverage шалгах
      - name: JUnit Тест ба JaCoCo Coverage Шалгах
        run: mvn test jacoco:check
        working-directory: ./src

      # JaCoCo тайлан үүсгэх
      - name: JaCoCo Тайлан Үүсгэх
        run: mvn jacoco:report
        working-directory: ./src
